class ProfileDecorator < Draper::Base
  EMPTY_GRAVATAR = "empty_gravatar.png"

  decorates :profile
  decorates_association :owned_tags

  def gravatar
    github.fetch(:gravatar, EMPTY_GRAVATAR)
  end

  def gists(tag)
    gists = Gist.find_page_by_tag_name_and_profile(h.params[:page],
                                                   tag.name,
                                                   profile)

    gists.collect! { |g| g.decorate }
  end

  private
  def github
    @github ||= if h.user_signed_in?
                  h.session["warden.user.user.session"].fetch(:github, {})
                else
                  {}
                end
  end

  # Accessing Helpers
  #   You can access any helper via a proxy
  #
  #   Normal Usage: helpers.number_to_currency(2)
  #   Abbreviated : h.number_to_currency(2)
  #
  #   Or, optionally enable "lazy helpers" by including this module:
  #     include Draper::LazyHelpers
  #   Then use the helpers with no proxy:
  #     number_to_currency(2)

  # Defining an Interface
  #   Control access to the wrapped subject"s methods using one of the following:
  #
  #   To allow only the listed methods (whitelist):
  #     allows :method1, :method2
  #
  #   To allow everything except the listed methods (blacklist):
  #     denies :method1, :method2

  # Presentation Methods
  #   Define your own instance methods, even overriding accessors
  #   generated by ActiveRecord:
  #
  #   def created_at
  #     h.content_tag :span, attributes["created_at"].strftime("%a %m/%d/%y"),
  #                   :class => "timestamp"
  #   end
end
