class ProfileDecorator < Draper::Base

  # Public: String of default gravatar png file
  EMPTY_GRAVATAR = "empty_gravatar.png"

  decorates :profile
  decorates_association :owned_tags

  # Public: When a user has a gravatar, use it for their profile avatar.
  #         Otherwise, use the default empty avatar.
  #
  # Examples
  #
  #   gravatar
  #   # => "empty_gravatar.png"
  #
  #   gravatar
  #   # => "https://1.gravatar.com/avatar/767fc9c115a1b989744c755db47feb60?s=200&r=pg&d=mm"
  #
  # Returns String to gravatar file.
  def gravatar
    github.fetch(:gravatar, EMPTY_GRAVATAR)
  end

  # Public: Gets all the profile's gists by a received tag, paginate the list
  #         and decorate each gist. Finally, return all the found gists. We
  #         do not decorate the profile's gists association with Draper because
  #         the tagged_with and page methods clobber the decorated association.
  #         Also, under the hood, the decorates_association macro collects and
  #         decoratres a collection, so our implementation is very similiar.
  #
  # tag - The Tag instance used to find gists.
  #
  # Returns an Array of paginated and decorated gists.
  def gists_for(tag)
    found = gists.tagged_with(tag.name, on: :descriptions).page(h.params[:page])
    found.collect! { |gist| gist.decorate }
  end

  private
  # Internal: Extract and memoize GitHub session key value pairs.
  #
  # Examples
  #
  #   github
  #   # => { :gravatar => "https://1.gravatar.com/avatar/767fc9c115a1b989744c755db47feb60?s=200&r=pg&d=mm" }
  #
  #   github
  #   # => {}
  #
  # Returns Hash of GitHub session.
  def github
    @github ||= if h.user_signed_in?
                  h.session["warden.user.user.session"].fetch(:github, {})
                else
                  {}
                end
  end

  # Accessing Helpers
  #   You can access any helper via a proxy
  #
  #   Normal Usage: helpers.number_to_currency(2)
  #   Abbreviated : h.number_to_currency(2)
  #
  #   Or, optionally enable "lazy helpers" by including this module:
  #     include Draper::LazyHelpers
  #   Then use the helpers with no proxy:
  #     number_to_currency(2)

  # Defining an Interface
  #   Control access to the wrapped subject"s methods using one of the following:
  #
  #   To allow only the listed methods (whitelist):
  #     allows :method1, :method2
  #
  #   To allow everything except the listed methods (blacklist):
  #     denies :method1, :method2

  # Presentation Methods
  #   Define your own instance methods, even overriding accessors
  #   generated by ActiveRecord:
  #
  #   def created_at
  #     h.content_tag :span, attributes["created_at"].strftime("%a %m/%d/%y"),
  #                   :class => "timestamp"
  #   end
end
