# Add account credentials and API keys here.
# See http://railsapps.github.com/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable and overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]
# Add application configuration variables here, as shown below.
#
# Environment variables required by MyGists
# GitHub Application
# @see https://github.com/settings/applications
GITHUB_APP_ID: APP_ID
GITHUB_APP_SECRET: APP_SECRET

# config/environment/production.rb
# GA.tracker
# @see http://support.google.com/analytics/bin/answer.py?hl=en&answer=1032385
GOOGLE_ANALYTICS_TRACKING_ID: UA-XXXXX-Y

# MyGists::Application.config.secret_token
# @see http://blog.phusion.nl/2013/01/04/securing-the-rails-session-secret/
SECRET_TOKEN: fallback_token_for_development

# config/newrelic.yml
# @see https://newrelic.com/docs/ruby/ruby-agent-configuration
NEW_RELIC_APP_NAME: YourMyGists
NEW_RELIC_LICENSE_KEY: new_relic_license_key

# In production, Redis is used for caching
# We set the environment variable key used to get Redis DSN
# On Heroku with RedisToGo:
# REDIS: redis://redistogo:86a1b907d54bf7010394bf316e183e67@subdomain.redistogo.com:9748/
# Our own Redis server:
REDIS: redis://localhost:6379/
